#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v3
# autospec commit: 750e50d
#
# Source0 file verified with key 0xCC2AF4472167BE03 (dickey@his.com)
#
Name     : dialog
Version  : 1.3.20240101
Release  : 42
URL      : https://invisible-mirror.net/archives/dialog/dialog-1.3-20240101.tgz
Source0  : https://invisible-mirror.net/archives/dialog/dialog-1.3-20240101.tgz
Source1  : https://invisible-mirror.net/archives/dialog/dialog-1.3-20240101.tgz.asc
Summary  : dialog - display dialog boxes from shell scripts
Group    : Development/Tools
License  : LGPL-2.1 MIT
Requires: dialog-bin = %{version}-%{release}
Requires: dialog-lib = %{version}-%{release}
Requires: dialog-license = %{version}-%{release}
Requires: dialog-locales = %{version}-%{release}
Requires: dialog-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : cppcheck
BuildRequires : ctags
BuildRequires : groff
BuildRequires : ncurses-dev
BuildRequires : pkgconfig(x11)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Dialog is a program that will let you present a variety of questions or
display messages using dialog boxes from a shell script.  These types
of dialog boxes are implemented (though not all are necessarily compiled
into dialog):

     buildlist, calendar, checklist, dselect, editbox, form, fselect,
     gauge, infobox, inputbox, inputmenu, menu, mixedform,
     mixedgauge, msgbox (message), passwordbox, passwordform, pause,
     prgbox, programbox, progressbox, radiolist, rangebox, tailbox,
     tailboxbg, textbox, timebox, treeview, and yesno (yes/no).

This package installs as "cdialog" to avoid conflict with other packages.

%package bin
Summary: bin components for the dialog package.
Group: Binaries
Requires: dialog-license = %{version}-%{release}

%description bin
bin components for the dialog package.


%package dev
Summary: dev components for the dialog package.
Group: Development
Requires: dialog-lib = %{version}-%{release}
Requires: dialog-bin = %{version}-%{release}
Provides: dialog-devel = %{version}-%{release}
Requires: dialog = %{version}-%{release}

%description dev
dev components for the dialog package.


%package lib
Summary: lib components for the dialog package.
Group: Libraries
Requires: dialog-license = %{version}-%{release}

%description lib
lib components for the dialog package.


%package license
Summary: license components for the dialog package.
Group: Default

%description license
license components for the dialog package.


%package locales
Summary: locales components for the dialog package.
Group: Default

%description locales
locales components for the dialog package.


%package man
Summary: man components for the dialog package.
Group: Default

%description man
man components for the dialog package.


%prep
%setup -q -n dialog-1.3-20240101
cd %{_builddir}/dialog-1.3-20240101
pushd ..
cp -a dialog-1.3-20240101 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1707074807
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
%configure --disable-static --enable-nls \
--with-libtool \
--with-ncursesw \
--includedir=%{_includedir}/dialog
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static --enable-nls \
--with-libtool \
--with-ncursesw \
--includedir=%{_includedir}/dialog
make  %{?_smp_mflags}
popd
%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1707074807
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/dialog
cp %{_builddir}/dialog-1.3-20240101/COPYING %{buildroot}/usr/share/package-licenses/dialog/545f380fb332eb41236596500913ff8d582e3ead || :
cp %{_builddir}/dialog-1.3-20240101/package/debian/copyright %{buildroot}/usr/share/package-licenses/dialog/fa09a07cbe14d96b119a527181654be32af7d7f2 || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
%find_lang dialog
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/dialog
/usr/bin/dialog
/usr/bin/dialog-config

%files dev
%defattr(-,root,root,-)
/usr/include/dialog/dialog.h
/usr/include/dialog/dlg_colors.h
/usr/include/dialog/dlg_config.h
/usr/include/dialog/dlg_keys.h
/usr/lib64/libdialog.so
/usr/share/man/man3/dialog.3

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libdialog.so.15.0.0
/usr/lib64/libdialog.so.15
/usr/lib64/libdialog.so.15.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/dialog/545f380fb332eb41236596500913ff8d582e3ead
/usr/share/package-licenses/dialog/fa09a07cbe14d96b119a527181654be32af7d7f2

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/dialog.1

%files locales -f dialog.lang
%defattr(-,root,root,-)

